config/routes.rb
GenRap::Application.routes.draw do
  resources :languages

  root :to => 'exams#pending'

  resources :users, :groups, :master_questions, :exam_definitions, :exams
  
  match "signup", :to => "users#new"
  match "login", :to => "sessions#login"
  match "logout", :to => "sessions#logout"
  match "def", to: "exam_definition#new"
  match "results/exam/:id", to: "exams#results", as: "exam_results"
  match "create/exam/:id", to: "exams#create", as: "create_exam"
  match "pending", to: "exams#pending"
  match "edit/:id", to: "exam_definition#edit"
  match "mystats", to: "stats#mystats"
  match "profstats", to: "stats#profstats"

  match "master_question/concepts_for_question" => "master_questions#concepts_for_question"
  match "master_question/subconcepts_for_question" => "master_questions#subconcepts_for_question"
  match "master_question/filtered_master_questions" => "master_questions#filtered_master_questions"
  match "master_question/transmiting_JSON" => "master_questions#transmiting_JSON"
  match "master_question/get_languages" => "master_questions#get_languages"

  match "exam/get_exams" => "exams#get_exams"

  match "exam_definition/exam_def" => "exam_definition#exam_def"

  match "group/get_groups" => "groups#get_groups"

  match "user/get_users" => "users#get_users"
  match "user/get_current_user" => "users#get_current_user"
  match "user/set_users_cantake" => "users#set_users_cantake"
  match "user/set_user_cantake_own" => "users#set_user_cantake_own"
  match "user/change_admin/:id" => "users#change_admin"
  match "user/change_professor/:id" => "users#change_professor"
  match "user/change_student/:id" => "users#change_student"

end

app/models/exam_definition.rb
#encoding: utf-8
class ExamDefinition < ActiveRecord::Base
  belongs_to :master_exam
  belongs_to :master_question
  has_one :language

  validates :master_exam,		:presence => true
  validates :master_question,	:presence => true
  validates :questionNum,	:presence => true,
  							:numericality => { :only_integer => true,
  										:greater_than_or_equal_to => 0 }
  validates :weight,		:presence => true,
  							:numericality => {  :greater_than_or_equal_to => 0.0,
  												:less_than_or_equal_to => 1.0 }

  attr_accessible :questionNum, :weight, :master_exam, :master_question, :language_id
end

app/controllers/exam_definition_controller.rb
#encoding: utf-8
class ExamDefinitionController < ApplicationController

  before_filter :authenticate_user

	def new
		@examDefinition = ExamDefinition.new
		@master_questions = MasterQuestion.all_languages
		@examUsers = nil

    if check_prof
      render "new"
    else
      render "new_student"
    end
	end

	def create
    if check_prof
  		@examDefinition = ExamDefinition.new(params[:examID])
  		@examDefinition.utype = 0
  		
  		if @examDefinition.save
  			flash[:notice] = "Definición de examen creada de manera exitosa."
  		else
  			flash[:error] = "Los datos no son válidos."
  		end

  		redirect_to root_path
    else
        flash[:error] = "Acceso restringido."
        redirect_to root_path
    end
	end

	# def edit
	# end

	# def update
	# end

	# def destroy
	# end

	# def index
	# end

	def exam_def
    #este no debería de ir aquí pero marca error al intentarlo hacer en otro controlador
    #parece que una vez que hago un get en este controlador, ya no puedo cambiarlo.
    #por lo tanto los queries los voy a hacer aquí
    hash = params[:hash]
    exam_name = params[:exam_name]
    duracion_name = params[:duracion_name]
    number_of_attempts = params[:number_of_attempts]
    creationYear = params[:creationYear].to_i
    creationMonth = params[:creationMonth].to_i
    creationDay = params[:creationDay].to_i
    creationHour = params[:creationHour].to_i
    creationMinute = params[:creationMinute].to_i
    startYear = params[:startYear].to_i
    startMonth = params[:startMonth].to_i
    startDay = params[:startDay].to_i
    startHour = params[:startHour].to_i
    startMinute = params[:startMinute].to_i
    endYear = params[:endYear].to_i
    endMonth = params[:endMonth].to_i
    endDay = params[:endDay].to_i
    endHour = params[:endHour].to_i
    endMinute = params[:endMinute].to_i

    timeZone = "Monterrey"

    user = User.find_by_id session[:user_id]
    master_exam = MasterExam.create(
      attempts: number_of_attempts,
      name: exam_name,
      duracion: duracion_name,
      dateCreation: Time.strptime("#{creationYear}-#{creationMonth}-#{creationDay} #{creationHour}:#{creationMinute}", '%Y-%m-%d %H:%M').in_time_zone(timeZone),
      startDate: Time.strptime("#{startYear}-#{startMonth}-#{startDay} #{startHour}:#{startMinute}", '%Y-%m-%d %H:%M').in_time_zone(timeZone),
      finishDate: Time.strptime("#{endYear}-#{endMonth}-#{endDay} #{endHour}:#{endMinute}", '%Y-%m-%d %H:%M').in_time_zone(timeZone),
      user: user
    )
        
    hash.each_with_index do |(key, value), index|
      ExamDefinition.create( 
        master_question: MasterQuestion.find_by_id( hash[key]['master_question_id'].to_i ),
        master_exam: MasterExam.find_by_id(master_exam.id),
        questionNum: index+1, 
        weight: hash[key]['value'].to_f
      )
    end

    if check_prof
      flash[:notice] = "Examen agregado exitosamente"
    else
      flash[:notice] = "Ejercicio creado exitosamente"
    end

    respond_to do |format|
      format.json { render json: hash.to_json }
    end

	end
end

app/views/exam_definition/_form.html.erb
<%= simple_form_for @examDefinition, url: new_exam_definition_path do |f| %>

	<h3>Datos Generales</h3>

	<%= label_tag "tag000", "Nombre del Examen:" %>
	<%= text_field "name", "exam", "size" => 5, placeholder:"Nombre" %>

	<br />
	<%= f.collection_select :id, Language.all, :id, :name %>
	<br/>

	<%= label_tag "tag0000", "Número de Intentos:" %>
	<!-- <%= text_field "attempts", "number", "size" => 5, placeholder:"Número" %> -->
	<select id="attempts_number" style="width: 80px">
	  <option value="1" selected>1</option>
	  <option value="2">2</option>
	  <option value="3">3</option>
	  <option value="4">4</option>
	  <option value="5">5</option>
	  <option value="6">6</option>
	  <option value="7">7</option>
	  <option value="8">8</option>
	  <option value="9">9</option>
	  <option value="10">10</option>
	</select>


<<<<<<< HEAD
=======
	<%= label_tag "tag000", "Duración del examen (minutos)" %>
	<%= text_field "duracion", "exam", placeholder:"Duración del examen" %> 



>>>>>>> 4215ad88fc135059a726234466e929f7a388e74d
	<h3>Preguntas</h3>

	<table>
		<tr>
			<td>

				<select id="concept">
					<option>Selecciona un tema</option>
				</select>
				<br/>
				<select id="subconcept">
					<option>Selecciona un concepto</option>
				</select>

			</td>
			<td>
				<table id="filteredMQ" class="table"></table>
			</td>
		</tr>
	</table>
	<br />
	<table id="examInquiriesHeaders" class="table">
		<tbody>
			<tr class="info">
				<td>Reactivo</td>
				<td>Valor</td>
				<td></td>
			</tr>
		</tbody>
	</table>
	<table id="examInquiries" class="table table-striped"></table>





	<h3>Fechas</h3>

	<table class="table table-bordered">
		<tr>
			<td>
				Inicio
			</td>
			<td>
				<%= label_tag "tag1", "Fecha Inicio:" %>
				<%= text_field nil, nil, {:class => 'date_picker', :id => "datestart"} %>
			</td>
			<td>
				<%= label_tag "tag2", "Hora Inicio:" %>
				<%= time_select "start", "Time",
												{order: [:hour, :minute], default: Time.now},
												{style: 'width: 80px'}
					%>
			</td>
		</tr>
		<tr>
			<td>
				Fin
			</td>
			<td>
				<%= label_tag "tag3", "Fecha de Entrega:" %>
				<%= text_field nil, nil, {:class => 'date_picker', :id => "dateend"} %>
			</td>
			<td>
				<%= label_tag "tag4", "Hora de Entrega:" %>
				<%= time_select "end", "Time",
												{order: [:hour, :minute], default: { hour: 23, minute: 59 }},
												{style: 'width: 80px'}
					%>
			</td>
		</tr>
	</table>






	<h3>Grupos</h3>
	<div id= "groups"> </div>

	<br />
	<br />
	<br />

	<div class="control-group">
		<div class="controls">	
			<%= f.submit "Crear Examen", {type:"button", id:"submit", :class => "btn btn-primary", :style => ""} %>
			<%= link_to("Calcular Valores", "#", {:class => "btn", :style => "", :id => "calculateValues"}) %>
			<!-- <%= link_to("Borrar Todo", "#", {:class => "btn", :style => "", :id => "eraseEverything"}) %> -->
			<!-- <button type="button" id="calculateValues">Calcular Valores</button> -->
			<!-- <button type="button" id="eraseEverything">Borrar Todo</button> -->
		</div>
	</div>
	<div class="control-group">
		<div class="controls">
			<!-- <%= link_to("Continuar [Selección de Usuarios]", "#", {:class => "btn", :style => "", :id => "addUsers"}) %> -->
			<!-- <button type="button" id="addUsers">Continuar [Selección de Usuarios]</button> -->
		</div>
	</div>

	<label id="get_groups_SPECIALHIDDENTAG" />
	

<% end %>