config/routes.rb
GenRap::Application.routes.draw do
  resources :languages

  root :to => 'exams#pending'

  resources :users, :groups, :master_questions, :exam_definitions, :exams
  
  match "signup", :to => "users#new"
  match "login", :to => "sessions#login"
  match "logout", :to => "sessions#logout"
  match "def", to: "exam_definition#new"
  match "results/exam/:id", to: "exams#results", as: "exam_results"
  match "create/exam/:id", to: "exams#create", as: "create_exam"
  match "pending", to: "exams#pending"
  match "edit/:id", to: "exam_definition#edit"
  match "mystats", to: "stats#mystats"
  match "profstats", to: "stats#profstats"

  match "master_question/concepts_for_question" => "master_questions#concepts_for_question"
  match "master_question/subconcepts_for_question" => "master_questions#subconcepts_for_question"
  match "master_question/filtered_master_questions" => "master_questions#filtered_master_questions"
  match "master_question/transmiting_JSON" => "master_questions#transmiting_JSON"
  match "master_question/get_languages" => "master_questions#get_languages"

  match "exam/get_exams" => "exams#get_exams"

  match "exam_definition/exam_def" => "exam_definition#exam_def"

  match "group/get_groups" => "groups#get_groups"

  match "user/get_users" => "users#get_users"
  match "user/get_current_user" => "users#get_current_user"
  match "user/set_users_cantake" => "users#set_users_cantake"
  match "user/set_user_cantake_own" => "users#set_user_cantake_own"
  match "user/change_admin/:id" => "users#change_admin"
  match "user/change_professor/:id" => "users#change_professor"
  match "user/change_student/:id" => "users#change_student"

end

app/models/exam.rb
#encoding: utf-8
class Exam < ActiveRecord::Base
  belongs_to :master_exam
  belongs_to :user
  has_many :questions
  has_one :language

  validates :state,	:presence => true
  validates :score,	:presence => true,
  					:numericality => { :greater_than_or_equal_to => 0.0,
  										:less_than_or_equal_to => 100.0 }

  attr_accessible :date, :questions_attributes, :score
  accepts_nested_attributes_for :questions

  before_save :check_attempts

  # private
	  def check_attempts
	  	state = self.state.to_i
		attempts = Exam.where("master_exam_id = ? and user_id = ?", self.master_exam_id, self.user_id).size
		allowedAttempts = MasterExam.find(self.master_exam_id).attempts
		if attempts > allowedAttempts || state >= 2
			false
		elsif state >= -1
		  	state = state + 1
		  	self.state = state.to_s
	  	else
	  		false
	  	end
	  end


  def self.createInstance(master_exam_id, user_id)
  		# session = Hash.new
  		# session[:user_id] = 9

  		ActiveRecord::Base.transaction do
			exam = Exam.new

			# Create exam
			exam.master_exam = MasterExam.find(master_exam_id)
			exam.user = User.find user_id
			exam.state = "-1"
			exam.date = Time.now
			exam.score = 0
			
			user = User.find(user_id)
			
			if exam.master_exam.users.include? user
				attemptN = Exam.where("master_exam_id = ? and user_id = ?", master_exam_id, user_id).size

				if attemptN < exam.master_exam.attempts
					exam.attemptnumber = attemptN + 1

					if exam.save
						# flash[:notice] = "Examen creado de manera exitosa."
						puts "Examen creado de manera exitosa."
					else
						# flash[:error] = "No se pudo crear el examen."
						puts "No se pudo crear el examen."
						raise ActiveRecord::Rollback
					end
				else
					# flash[:error] = "Se han agotado los attempts."
					puts "Se han agotado los attempts."
					raise ActiveRecord::Rollback
				end
			else
				# flash[:error] = "Usuario no puede tomar este examen."
				puts "Usuario no puede tomar este examen."
				raise ActiveRecord::Rollback
			end

			# Create questions
			e_definition = ExamDefinition.where("master_exam_id = ?", master_exam_id)
			for mQuestion in e_definition
				master_question = MasterQuestion.find(mQuestion.master_question_id)
				inquiry = master_question.inquiry

				# We generate random question
				randomizer = master_question.randomizer
				full_randomizer_path = File.dirname(__FILE__) + "/../helpers/r/" + randomizer + '.rb'
				load full_randomizer_path
				puts "loaded " + full_randomizer_path
				values = randomize(inquiry)
				# puts "values " + values.to_s

				# We generate values, correctAns
				solver = master_question.solver
				full_solver_path = File.dirname(__FILE__) + "/../helpers/s/" + solver + '.rb'
				load full_solver_path
				puts "loaded " + full_solver_path
				answers, correctAns = solve(inquiry, values)
				# puts "answers " + answers.to_s
				# puts "correctAns " + correctAns.to_s

				# We finally create the question
				question = Question.new
				# puts "exam " + exam.to_s
				question.exam = exam
				question.master_question = master_question
				question.questionNum = mQuestion.questionNum
				question.values = values
				question.answers = answers
				question.correctAns = correctAns
				question.givenAns = ""

				if question.save
					# flash[:notice] = "Pregunta creada de manera exitosa."
					puts "Pregunta creada de manera exitosa."
				else
					# flash[:error] = "No se pudo crear la pregunta."
					puts "No se pudo crear la pregunta."
					raise ActiveRecord::Rollback
				end
			end #end for

			#Return exam
			exam

		end  #end transaction
	end #end method

end

app/controllers/exams_controller.rb
#encoding: utf-8
class ExamsController < ApplicationController

	helper_method :who_cantake_masterExam

	before_filter :authenticate_user, :except => [:who_cantake_masterExam]

	def new
		@exam = Exam.new
	end

	def index
		if check_admin
			@masterExams = MasterExam.all
		elsif check_prof
			@masterExams = MasterExam.where("user_id = ?", @current_user.id)
		else
			flash[:error] = "Acceso restringido."
			redirect_to(root_path)
		 end
	end

	def pending
		@masterExams = Array.new
		@attempts_exams = Array.new

		@masterExercises = Array.new
		@exer_info = Array.new

		# Se obtienen los examenes cuya fecha de inicio sea menor a la actual y fecha de termino sea mayor a la actual
		# Además, estos deben ser creados por personas diferentes al usuario actual
		availableExams = MasterExam.where("startDate <= ? AND finishDate >= ? AND user_id <> ?", Time.now, Time.now, @current_user.id)
		
		# Para cada uno de estos examenes, se agrega el master exam y los intentos actuales a los arreglos correspondientes
		availableExams.each do |masterExam|
			# Se obtienen los usuarios relacionados con este examen
			validUsers = who_cantake_masterExam(masterExam.id)
			# Se valida que el usuario actual sea un usuario valido y que haya intentos restantes
			if validUsers.include?(@current_user.id) and Exam.where("master_exam_id = ? and user_id = ?", masterExam.id, @current_user.id).size < masterExam.attempts
				@masterExams.push(masterExam)
				# Se agrega a la lista de intentos, la cantidad de intentos del examen encontrado
				@attempts_exams.push(Exam.where("master_exam_id = ? and user_id = ?", masterExam.id, @current_user.id).size)
			end
		end

		# Se obtienen los examenes (ejercicios) creados por uno mismo, como ejercicios
		availableExercices = MasterExam.where("user_id = ?", @current_user.id)
		
		# Para cada uno de estos examenes, se agrega el master exam y el promedio de los intentos actuales a los arreglos correspondientes
		availableExercices.each do |masterExam|
			# Se obtienen los usuarios relacionados con este examen
			validUsers = who_cantake_masterExam(masterExam.id)
			# Se valida que el usuario actual sea un usuario valido
			if validUsers.include?(@current_user.id)
				actual_exams = Exam.where("master_exam_id = ? and user_id = ?", masterExam.id, @current_user.id)
				@masterExercises.push(masterExam)
				if actual_exams.length > 0
					grade = actual_exams.map { |e| e.score }.inject{|sum,x| sum + x }
					grade = grade / actual_exams.length.to_f
				else
					grade = "-"
				end
				@exer_info.push([grade, actual_exams.length])
			end
		end
	end

	def create
		masterExam = MasterExam.find(params[:id])
		creatorId = masterExam.user_id
		available = false
		if creatorId == @current_user.id
			# La fecha de creación no importa, es un ejercicio
			available = true
		else
			#La fecha de creación si importa, es un examen de alguien más
			if masterExam.startDate <= Time.now && masterExam.finishDate >= Time.now
				available = true
			end
		end
		@attempts = Exam.where("master_exam_id = ? and user_id = ?", params[:id], @current_user.id).size
		validUsers = who_cantake_masterExam(masterExam.id)

		if available && (check_prof || validUsers.include?(@current_user.id))

			# Se crea una instancia del examen para el usuario actual
			exam = Exam.createInstance(params[:id],@current_user.id)
			if exam != nil
				# Redirigir a editar el examen para contestarlo
				redirect_to :action => "edit", :id => exam.id
			elsif @attempts >= masterExam.attempts
				flash[:notice] = "Numero de intentos excedido."
				redirect_to(pending_path)
			else
				flash[:error] = "Error al crear el exámen. Intentos actuales: "+@attempts.to_s+"."
				redirect_to(pending_path)
			end
			#Modificar el estado del master exam de dicho usuario
			# @masterExam = MasterExam.find(params[:id])
			#Disminuir un intento cuando se entra al examen
			# @masterExam.attempts = @masterExam.attempts - 1;
		else
			flash[:error] = "Exámen no disponible."
			redirect_to(pending_path)
		end
	end


	def edit
		# Se verifica que el administrador sea el que está editando o que el examen sea del usuario actual y que el estado del examen sea 0 (creado)
		if check_prof || (@current_user.id.to_i == Exam.find(params[:id]).user_id.to_i && Exam.find(params[:id]).state.to_i == 0)
			# Declarar el examen como comenzado
			@exam = Exam.find(params[:id])
			#master_examen es un objeto
			@examenMaestro = @exam.master_exam
			# Se guarda el examen para cambiarse a comenzado
			if !@exam.save
				flash[:error] = "Error al obtener el examen."
				redirect_to(pending_path)
			end
		else
			flash[:error] = "Acceso restringido."
			redirect_to(pending_path)
		end
	end


	def show
		if check_prof || @current_user.id == Exam.find(params[:id]).user_id
			@exam = Exam.find(params[:id])
		else
			flash[:error] = "Acceso restringido."
			redirect_to(pending_path)
		end
	end

	def update
		if check_prof || @current_user.id == Exam.find(params[:id]).user_id
			@exam = Exam.find(params[:id])
			
			masterExam = @exam.master_exam

			# Checar que la fecha del examen sea valida
			if masterExam.startDate <= Time.now && masterExam.finishDate >= Time.now
				examenTomado = @exam
				#checara que la hora en la que se guarda el servidor esta dentro del tiempo de duración y 30 segundos del alert que muestra
				horaMaxima = examenTomado.date + (masterExam.duracion*60) + 30
				if Time.now <= horaMaxima
					score = 0
					masterExamId = masterExam.id

					# Para cada pregunta, se verifica la respuesta
					@exam.questions.each do |question|

						masterQuestionId = question.master_question_id
						questionId = params[":questions"][question.id.to_s]
						givenAns = questionId["givenAns"]
						question.update_attributes(givenAns: givenAns)

						# Si la respuesta dada es correcta, se agrega la cantidad al score
						if givenAns == question.correctAns
							questionNum = question.questionNum
							examDef = ExamDefinition.where("master_exam_id = ? and master_question_id = ? and questionNum = ?", masterExamId, masterQuestionId, questionNum).first
							weight = examDef.weight
							score = score + weight*100
						end
					end

					# Se actualiza el score del examen
				    if @exam.update_attributes(score: score)
						flash[:notice] = 'El exámen fue registrado de manera correcta.'
				    else
				    	flash[:error] = "Error al guardar el exámen."
				    	redirect_to(root_path)
				    end
			    	redirect_to :action => "results", :id => @exam.id
			    end
		    else
		    	flash[:error] = "Examen no disponible."
		    	redirect_to(root_path)
		    end
		else
			flash[:error] = "Acceso restringido."
			redirect_to(root_path)
		end
	end

	def results
		exam = Exam.find(params[:id])
		validUsers = Array.new
		validUsers.push(exam.user_id)

		masterExam = MasterExam.find(exam.master_exam_id)
		examCreator = masterExam.user_id

		validUsers.push(examCreator)


		if check_prof || validUsers.include?(@current_user.id)
			@exam = exam
		else
			flash[:error] = "Acceso restringido."
			redirect_to(root_path)
		end
	end

	#gets a list of users that can take the masterExam
	# private
		def who_cantake_masterExam(masterExamId)
			validUsers = Array.new

			masterExam = MasterExam.find(masterExamId)
			masterExam.cantakes.each do |cantake|
				validUsers.push(cantake.user_id) 
			end
			validUsers
		end
 	
end

app/helpers/exams_helper.rb
module ExamsHelper

	def format_values(values)
		JSON.parse("{" << values.gsub("-","").gsub(/(\^\d+)/,'"\\1"').gsub("\n",",").sub(",","").gsub(/(.*),(.*)/,'\\1\\2') << "}")
	end

	def format_answers(answers)
		answers.gsub("-","").gsub("\n",",").sub(",","").gsub(/(.*),(.*)/,'\\1\\2').split(/,/)
	end

	#Funcion que acomoada las respuestas de los examenes de manera aleatoria
	def random_answers(answers)
		#Se crea un arreglo temporal para guardar los valores en sus nuevas posiciones
		answersTemp = Array.new(answers.length, "0:0")
		count = answers.length
		randNumber = Random.rand(1..answers.length)
		i = 0
		i.to_i
		#Se recorre el arreglo de respuestas para cambiar las pocisiones
        while i < count 
        	#Si la posicion random ya tiene un valor asignado, se genera otro numero aleatorio
			while answersTemp[randNumber-1].to_s != "0:0"
				randNumber = Random.rand(1..answers.length)
			end
			#Se guarda el valor del arreglo de respuetas en el arreglo temporal
			answersTemp[randNumber-1] = answers[i]
			i = i + 1
 		end
 		#Se regresa el arreglo temporal con los valores en las nuevas posiciones
 		return answersTemp
	end

	def check_correct_anwers(answers, correct)
		correctAnswer = answers[correct].to_s
		count = answers.length
		i = 0
		i.to_i
		while i < count 
	    	if i != correct
	    		if answers[i].to_s == correctAnswer
	    			if answers[i].to_s.match(/\A[+-]?\d+?(\.\d+)?\Z/) != nil
	    				answers[i] = answers[i] + Random.rand(1..10)
	    			end
	    		end
	    	end
			i = i + 1
		end
		return answers
	end
end

app/views/exams/_form.html.erb
<%= simple_form_for @exam do |exam_field| %>
	<fieldset>
		<% answers = Array.new %>
		<% @exam.questions.each do |question| %>
			<% inquiry = question.master_question.inquiry %>
			<!-- gsub 1 no se debe de necesitar, hay algo mal en question.values -> randomizer -->
			<% parsed = format_values(question.values) %>
			<% parsed = parsed.stringify_keys() %>
			<% parsed.each do |key, value| %>
				<p><% inquiry = inquiry.gsub(key,value.to_s) %></p>
			<% end %>
			<p><%= question.questionNum.to_s+".  "+inquiry %></p>

			<%= simple_fields_for ":questions[]", question do |question_field| %>
				<% answers = format_answers(question.answers) %>
				<% answers = random_answers(answers) %>
				<%= question_field.select :givenAns, answers.map{ |ansNum| [ansNum.split(": ").second, ansNum.split(": ").first] } %>
			<% end %>
		<% end %>

		<div class="control-group">
			<div class="controls">
				<%= exam_field.button :submit, "Enviar" %>
			</div>
		</div>
	</fieldset>

<% end %>

app/views/exams/edit.html.erb
<div class="hero-unit">

	<h3  style="text-align: center;">Exámen</h3>
    <div  style="background:yellow;"><h4> Duración del examen: <span id="examen"><%= 
    #TOMA EL VALOR DE DURACION DE LA TABLA DE MASTER_EXAM
     @examenMaestro.duracion 
    %>:00</span> minutos</h4></div>
	<%= render 'form' %>

	<% if @exam.errors.any? %>
		<ul>
			<% for message_error in @exam.errors.full_messages %>
			<li>- <%= message_error %></li>
			<% end %>
		</ul>
	<% end %>


</div>


<script type="text/javascript">
 var tiempo = <%= 
     @examenMaestro.duracion 
    %>;				
   var tiempoSeg = tiempo*60;
   //calcula las horas que tiene la duracion.
   var hrs = Math.floor(tiempoSeg/3600);
		var timer = $.timer(
			function() {
				var hrs = Math.floor(tiempoSeg/3600);
				var mins = Math.floor((tiempoSeg % 3600)/60);
				//si es mayor a 60 min agrega la hora a los minutos
				if(hrs > 0 ){
					mins = mins + 60;
				} 
				var secs = tiempoSeg % 60;
				var tock = /*(hrs < 10 ? "0" : "" ) + hrs+ ":" */
				         + (mins < 10 ? "0" : "" ) + mins + ":" 
				         + (secs < 10 ? "0" : "" ) + secs;
				 $('#examen').html(tock);
				 tiempoSeg--;
				 //si el tiempo es de segundos
				 if(tiempoSeg <= 60){
				 		console.log("Se te acabara el tiempo");
				 }
				 if(tiempoSeg == 0){
				 	//se debe de cerrar
				 }
			},
			1000,
			true
		);	
	//Para que no mande alert al dar clic en boton de Enviar
	$(".edit_exam").on("submit", function(e) {
		window.onbeforeunload = null;	//se cancela la funcion onbeforeunload
	})

	//funcion para enviar una alerta al momento en que el usuario actualiza o cierra la pestaña
	window.onbeforeunload = function (e) {
            e = e || window.event;
            var y = e.pageY || e.clientY;
            if (y < 0){
                return "¿Seguro que deseas salir del examen?";
            }
            else {
                return "Al actualizar o cerrar la página perderas un intento del examen";
            }
            
            

    }
    /*
    setInterval(function(){alert("Hello")},800);
    window.onload=function(){var timer = $.timer(function() {
                alert('This message was sent by a timer.');
        });

        timer.set({ time : 5000, autostart : true });};
    */
    
</script>

app/views/exams/index.html.erb
<div class="table">
  <% if @masterExams != nil %>
    
    <%= table_for @masterExams, html: {id: 'exams', class: 'summary table table-striped table-bordered table-condensed'} do -%>
      <% column title: 'Nombre' do |masterExam| %>
        <% #link_to(masterExam.name, create_exam_path(masterExam.id), confirm: "Are you sure?") %>
        <% link_to(masterExam.name, create_exam_path(masterExam.id)) %>
      <% end %>
      <% column :attempts, title: 'Intentos máximos' %>
      <% column :startDate, title: 'Inicio' %>
      <% column :finishDate, title: 'Fin' %>
    <% end %>

  <% else %>
    
    <table class="table table-striped table-bordered table-condensed">
      <tbody>
        <tr>
          <td>No hay exámenes disponibles</td>
        </tr>
      </tbody>
    </table>
  
  <% end %>
</div>

app/views/exams/pending.html.erb
<div class="table">

  <h3>Exámenes Disponibles</h3>
  <% if @masterExams.length > 0 && @attempts_exams.length > 0 %>
    <% count = 0 %>

    <table class="summary table table-striped table-bordered table-condensed">
      <tbody>
        <tr>
          <th>Nombre</th><th>Intentos actuales</th><th>Intentos máximos</th><th>Inicio</th><th>Fin</th>
        </tr>
        <% @masterExams.each do |masterExam| %>
          <tr>
            <td><%= link_to(masterExam.name, create_exam_path(masterExam.id), confirm: "¿Seguro que deseas tomar este exámen? Nota: No podrás regresar una vez comenzado.") %></td>
            <td><%= @attempts_exams[count] %><% count = count + 1 %></td>
            <td><%= masterExam.attempts %></td>
            <td><%= masterExam.startDate %></td>
            <td><%= masterExam.finishDate %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <% else %>
    
    <table class="table table-striped table-bordered table-condensed">
      <tbody>
        <tr>
          <td>No hay exámenes disponibles</td>
        </tr>
      </tbody>
    </table>
  
  <% end %>


  <h3>Ejercicios Disponibles</h3>
  <% if @masterExercises.length > 0 %>
    <% count = 0 %>

    <table class="summary table table-striped table-bordered table-condensed">
      <tbody>
        <tr>
          <th>Nombre</th>
          <th>Calificación Promedio</th>
          <th>Veces Tomado</th>
        </tr>
        <% @masterExercises.each do |masterExam| %>
          <tr>
            <td><%= link_to(masterExam.name, create_exam_path(masterExam.id), :target => "_blank", :confirm => "¿Seguro que deseas tomar este exámen?\nNota: No podrás regresar una vez comenzado." ) %></td>
            <td><%= @exer_info[count][0] %></td>
            <td><%= @exer_info[count][1] %><% count = count + 1 %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <% else %>
    
    <table class="table table-striped table-bordered table-condensed">
      <tbody>
        <tr>
          <td>No hay ejercicios disponibles</td>
        </tr>
      </tbody>
    </table>
  
  <% end %>
</div>

app/views/exams/results.html.erb
<div class="table">
  <% if @exam != nil %>
    
    <table id="results" class="summary table table-striped table-bordered table-condensed">
      <tbody>
        <tr>
          <th>Intento</th>
          <th>Calificación</th>
          <th>Fecha</th>
        </tr>
        <tr>
          <td><%= @exam.attemptnumber %></td>
          <td><%= @exam.score %></td>
          <td><%= @exam.updated_at %></td>
        </tr>
      </tbody>
    </table>

 <!--
    <% #if check_admin 
    %>
      <%= #link_to "Continuar", exams_path, class: "btn" 
      %>
    <% #else 
    %>
      <%= #link_to "Continuar", pending_path, class: "btn" 
      %>
    <% #end 
    %>
  -->
 
      <%= link_to "Continuar", pending_path, class: "btn" %>
    

  <% else %>
    
    <table class="table table-striped table-bordered table-condensed">
      <tbody>
        <tr>
          <td>Hubo un error al extraer los resultados de su examen.</td>
        </tr>
      </tbody>
    </table>
  
  <% end %>
</div>